---
# Cleanup System V init

- name: Remove obsolete config files if System V init
  file:
    path: >-
      {{ modprobe_etc_sysconfig_modules_dir }}/{{ modprobe_item.name }}.modules
    state: absent
  loop: >-
    {{ (modprobe_modules_to_manage
        | selectattr("state", "equalto", "deactivated")
        | list)
       + (modprobe_modules_to_manage
          | selectattr("state", "equalto", "blacklisted")
          | list) }}
  loop_control:
    loop_var: modprobe_item
    label: "{{ modprobe_item.name }}"
  tags:
    - role::modprobe::cleanup
    - role::modprobe::cleanup::systemv
