---

- name: Create config files for blacklisted modules
  become: yes
  ansible.builtin.template:
    src: blacklisted.j2
    dest: "{{ modprobe_d_dir }}/{{ modprobe_item.name }}.conf"
    owner: root
    group: root
    mode: '0644'
  loop: >-
    {{ modprobe_modules_to_manage
       | selectattr("state", "equalto", "blacklisted")
       | list }}
  loop_control:
    loop_var: modprobe_item
    label: "{{ modprobe_item.name }}"
  notify:
    - modprobe unload modules
  tags:
    - role::modprobe::blacklisted
