- block:
    - name: create config files for blacklisted modules
      template:
        src: module_blacklisted.j2
        dest: >-
          {{ modprobe_default_dir }}/{{ module.name }}.conf
      loop: >-
        {{ modprobe_modules_managed
           | selectattr("state", "equalto", "blacklisted")
           | list }}
      loop_control:
        loop_var: module
        label: "{{ module.name }}"
      notify:
        - modprobe_unload_module

  tags:
    - role::modprobe::blacklisted
