---
# Cleanup tasks

- block:
    - include_tasks: systemd/cleanup.yml
      when: ansible_facts.service_mgr == "systemd"

    - include_tasks: systemv/cleanup.yml
      when: ansible_facts.service_mgr != "systemd"
  tags:
    - role::modprobe::cleanup
    - role::modprobe::cleanup::systemd
    - role::modprobe::cleanup::systemv
