---
# Manage deactvated modules

- name: Create config files for deactivated modules
  become: yes
  template:
    src: deactivate.j2
    dest: >-
      {{ modprobe_d_dir }}/{{ modprobe_item.name }}.conf
    owner: root
    group: root
    mode: '0644'
  loop: >-
    {{ modprobe_modules_to_manage
       | selectattr("state", "equalto", "deactivated")
       | list }}
  loop_control:
    loop_var: modprobe_item
    label: "{{ modprobe_item.name }}"
  notify:
    - modprobe unload modules
  tags:
    - role::modprobe::deactivated
