- block:
    - name: create config files for deactivated modules
      template:
        src: module_deactivate.j2
        dest: >-
          {{ modprobe_default_dir }}/{{ module.name }}.conf
      loop: >-
        {{ modprobe_modules_manage
           | selectattr("state", "equalto", "deactivated")
           | list }}
      loop_control:
        loop_var: module
        label: "{{ module.name }}"
      notify:
        - modprobe_unload_module

  tags:
    - role::modprobe::deactivated
