- block:
    - name: setup fact with zones loaded from host variables
      include_role:
        name: amtega.select_hostvars
        apply:
          tags:
            - role::modprobe
            - role::modprobe::init
      vars:
        select_hostvars_pattern: "^modprobe_module_.*"
        select_hostvars_fact_name: modprobe_hostvars_modules
        select_hostvars_output_type: list
      when: modprobe_load_modules_from_hostvars

    - name: setup fact with zones that will be managed
      set_fact:
        modprobe_modules_managed: >-
          {{ (modprobe_load_modules_from_hostvars)
              | ternary([ modprobe_hostvars_modules ] | flatten
                        + modprobe_modules,
                        modprobe_modules) }}

  tags:
    - role::modprobe
    - role::modprobe::init
