---

- name: Setup modproble
  block:
    - ansible.builtin.include_tasks: blacklist.yml
      tags:
        - role::modprobe::blacklist

    - ansible.builtin.include_tasks: deactivate.yml
      tags:
        - role::modprobe::deactivated

    - ansible.builtin.include_tasks: cleanup.yml
      tags:
        - role::modprobe::cleanup
        - role::modprobe::cleanup::systemd
        - role::modprobe::cleanup::systemv

    - ansible.builtin.include_tasks: configure.yml
      tags:
        - role::modprobe::configure
        - role::modprobe::configure::systemd
        - role::modprobe::configure::systemv
  tags:
    - role::modprobe
