---
# Role handlers

- name: Load modules
  modprobe:
    name: "{{ modprobe_item.name }}"
    state: present
  loop: >-
    {{ modprobe_modules_to_manage
       | selectattr("state", "equalto", "install")
       | list }}
  loop_control:
    loop_var: modprobe_item
    label: "{{ modprobe_item.name }}"
  listen: modprobe load modules

- name: Unload deactivated/blacklisted modules
  modprobe:
    name: "{{ modprobe_item.name }}"
    state: absent
  loop: >-
    {{ (modprobe_modules_to_manage
        | selectattr("state", "equalto", "deactivated")
        | list)
       + (modprobe_modules_to_manage
          | selectattr("state", "equalto", "blacklisted")
          | list) }}
  loop_control:
    loop_var: modprobe_item
    label: "{{ modprobe_item.name }}"
  listen: modprobe unload modules
