---

- name: Prepare testing environment python
  hosts: molecule_hosts_centos_6
  gather_facts: no
  become: yes
  tasks:
    - name: Setup packages
      raw: yum install -y libselinux-python
      changed_when: yes

    - name: Update system
      command: yum update -y
      when: yes
      args:
        warn: no

    - name: Reboot machine
      reboot:
